name: see why 4.3.0 is broken
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: try first region
        id: creds1
        uses: aws-actions/configure-aws-credentials@proxy-fix-test
        with: 
          role-to-assume: arn:aws:iam::891612571239:role/githubActionTest-Role-5YBrxygEBfRs
          aws-region: us-east-1
          output-credentials: true
          output-env-credentials: false

      - name: print stuff i guess
        run: | 
          echo "AWS_REGION=$AWS_REGION"
          echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
          echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"

