name: more session tags testing
on: [workflow_dispatch, workflow_call]

jobs:
    do-the-thing:
        name: test out session tags
        runs-on: ubuntu-24.04
        steps:
          - name: configure AWS Creds
            id: first-config-step
            uses: aws-actions/configure-aws-credentials@main
            with:
                role-to-assume: arn:aws:iam::884348119369:role/session-tags-testing-role
                aws-region: us-east-2
                role-duration-seconds: 3600
                audience: sts.amazonaws.com
                aws-access-key-id: ${{secrets.SESSION_TAGS_TESTING_AKID}}
                aws-secret-access-key: ${{secrets.SESSION_TAGS_TESTING_SECRET_AK}}
                custom-tags: '{"first-long-key": "first-long-val", "second-long-key": "second-long-val", "third-long-key": "third-long-val", "fourth-long-key": "fourth-long-val", "fifth-long-key": "fifth-long-val", "sixth-long-key": "sixth-long-val", "seventh-long-key": "seventh-long-val", "eighth-long-key": "eighth-long-val", "ninth-long-key": "ninth-long-val", "tenth-long-key": "tenth-long-val"}'
          - name: check creds
            run: aws sts get-caller-identity