name: codebuild test
on: [workflow_dispatch]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-CAWSC_self-hosted_Tester-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: printenv
      - name: check initial identity (confirm we are using codebuild service role)
        run: aws sts get-caller-identity
      
      - name: Login to Amazon ECR
        id: login-ecr-local
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: assume other role
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::884348119369:role/codebuild-test-role-2
          custom-tags: '{"first-long-key": "first-long-val", "second-long-key": "second-long-val", "third-long-key": "third-long-val", "fourth-long-key": "fourth-long-val", "fifth-long-key": "fifth-long-val", "sixth-long-key": "sixth-long-val", "seventh-long-key": "seventh-long-val", "eighth-long-key": "eighth-long-val", "ninth-long-key": "ninth-long-val", "tenth-long-key": "tenth-long-val"}'
      
      - name: check new identity (confirm we assumed the new role)
        run: aws sts get-caller-identity
