name: repo-secret creds test w other creds first
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: try first region
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::891612571239:role/githubActionTest-Role-5YBrxygEBfRs
          aws-region: us-east-1

      - name: print stuff i guess
        run: | 
          echo "AWS_REGION=$AWS_REGION"

      - name: Configure AWS - Region 2
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          output-credentials: true

      - name: Check Region 2
        run: |
          echo "AWS_REGION=$AWS_REGION"