name: repo-secret creds test w other creds first
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: try first region
        id: creds1
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with: 
          role-to-assume: arn:aws:iam::891612571239:role/githubActionTest-Role-5YBrxygEBfRs
          aws-region: us-east-1
          output-credentials: true

      - name: print stuff i guess
        run: | 
          echo "AWS_REGION=$AWS_REGION"
          echo "Expiration: steps.creds1.outputs.aws-expiration"
        
      - name: take a little nap
        run: sleep 20s

      - name: Configure AWS - Region 2
        id: creds2
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          output-credentials: true

      - name: Check Region 2
        env:
          FIRST_EXP: ${{ steps.creds1.outputs.aws-expiration }}
          SECOND_EXP: ${{ steps.creds2.outputs.aws-expiration }}
        run: |
          echo "First set of credentials expire at $FIRST_EXP"
          echo "Second set of credentials expire at $SECOND_EXP"