name: ecr creds test

on: 
    workflow_dispatch

jobs:
    login-to-aws:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
          - uses: actions/checkout@v4
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-region: ${{ secrets.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}