name: profile test static creds
on:
    workflow_dispatch

jobs:
    token-file-test:
        runs-on: ubuntu-latest
        steps:
            - name: make profile 1
              id: creds1
              uses: aws-actions/configure-aws-credentials@jfeddern-feat/multiple-profiles
              with: 
                role-to-assume: arn:aws:iam::884348119369:role/profile-test-1
                aws-region: us-east-1
                aws-access-key-id: ${{ secrets.PROFILE_1_AK_ID }}
                aws-secret-access-key: ${{ secrets.PROFILE_1_SECRET_AK }}
                aws-profile: TestProfile1
                role-chaining: true
              env:
                AWS_PROFILE: TestProfile1

            - name: can we look at buckets w profile
              run: aws s3 ls --profile TestProfile1

            - name: make profile 2
              id: creds2
              uses: aws-actions/configure-aws-credentials@jfeddern-feat/multiple-profiles
              with: 
                role-to-assume: arn:aws:iam::884348119369:role/profile-test-2
                aws-region: us-east-2
                aws-access-key-id: ${{ secrets.PROFILE_2_AK_ID }}
                aws-secret-access-key: ${{ secrets.PROFILE_2_SECRET_AK }}
                aws-profile: TestProfile2
                role-chaining: true
              env:
                AWS_PROFILE: TestProfile2

            - name: can we look at buckets w profile2
              run: aws --profile TestProfile2 s3api get-bucket-location --bucket lehmanmj-profile-test-2

            - name: can we still look at buckets w profile1
              run: aws s3 ls --profile TestProfile1

            - name: check env
              run: env
