name: profile test
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: try first region
        id: creds1
        uses: aws-actions/configure-aws-credentials@v6
        with: 
          role-to-assume: arn:aws:iam::884348119369:role/profile-test-1
          aws-region: us-east-1
          output-credentials: true
          output-env-credentials: false
          disable-retry: true

      - name: configure profile 
        run: |
            aws configure set aws_access_key_id ${{ steps.creds1.outputs.aws-access-key-id }} --profile TestProfile1
            aws configure set aws_secret_access_key ${{ steps.creds1.outputs.aws-secret-access-key }} --profile TestProfile1
            aws configure set aws_session_token ${{ steps.creds1.outputs.aws-session-token }} --profile TestProfile1

      - name: can we login w profile
        run: aws sts get-caller-identity --profile TestProfile1
