name: token file test
on:
    workflow_dispatch

jobs:
    token-file-test:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: get stuff
              uses: actions/checkout@v4
            - run: ls
            - name: grab token
              run: node fetch-token.js

            - name: make profile 1
              id: creds1
              uses: aws-actions/configure-aws-credentials@jfeddern-feat/multiple-profiles
              with: 
                role-to-assume: arn:aws:iam::884348119369:role/profile-test-1
                aws-region: us-east-1
                web-identity-token-file: token.txt
                output-credentials: true
                output-env-credentials: false
                disable-retry: true
                aws-profile: TestProfile1

            - name: can we look at buckets w profile
              run: aws s3 ls --profile TestProfile1


            - name: grab token again
              run: node fetch-token.js

            - name: make profile 2
              id: creds2
              uses: aws-actions/configure-aws-credentials@jfeddern-feat/multiple-profiles
              with: 
                role-to-assume: arn:aws:iam::884348119369:role/profile-test-2
                aws-region: us-east-2
                web-identity-token-file: token.txt
                output-credentials: true
                output-env-credentials: false
                disable-retry: true
                aws-profile: TestProfile2

            - name: can we look at buckets w profile2
              run: aws --profile TestProfile2 s3api get-bucket-location --bucket lehmanmj-profile-test-2

            - name: can we still look at buckets w profile1
              run: aws s3 ls --profile TestProfile1

            - name: look at our profiles 
              run: cat ~/.aws/credentials