name: profile test manual oidc
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: make directory
        run: mkdir ~/.aws


      - name: Configure AWS Profile
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' > ~/.aws/web_identity_token_filea
          aws configure set region us-west-2 --profile TestProfile1
          aws configure set role_arn "arn:aws:iam::884348119369:role/profile-test-1" --profile TestProfile1
          aws configure set web_identity_token_file "web_identity_token_filea" --profile TestProfile1

      - name: hi
        run: |
          pwd
          cd ~/.aws
          ls

      - name: check profile1 
        run: |
            pwd
            aws sts get-caller-identity --profile TestProfile1
      