name: profile test
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: check config
        run: |
          ls ~

      - name: check env
        run: |
          env


      - name: make profile 1
        id: first-profile
        uses: aws-actions/configure-aws-credentials@jfeddern-feat/multiple-profiles
        with: 
          role-to-assume: arn:aws:iam::884348119369:role/profile-test-1
          aws-region: us-east-1
          output-credentials: true
          output-env-credentials: false
          aws-profile: TestProfile1
        env:
          AWS_CONFIG_FILE: ''
          AWS_CREDENTIALS_FILE: ''

      - name: make profile 2
        id: second-profile
        uses: aws-actions/configure-aws-credentials@jfeddern-feat/multiple-profiles
        with: 
          role-to-assume: arn:aws:iam::884348119369:role/profile-test-2
          aws-region: us-east-2
          output-credentials: true
          output-env-credentials: false
          aws-profile: TestProfile2

      - name: check profile1 
        run: aws sts get-caller-identity --profile TestProfile1
      
      - name: check profile2
        run: aws sts get-caller-identity --profile TestProfile2
      
      