name: 111aaa static new test
on: workflow_dispatch

jobs:
    static_assumeRole:
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request.user.login == 'aws-sdk-osds' && github.repository == 'aws-actions/configure-aws-credentials') }}
        permissions:
            id-token: write
        strategy: 
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        name: Static IAM creds test
        steps:
            #UNCOMMENT THIS ONE
        #- name: checkout
            #uses: actions/checkout@v5
            #with:
                #fetch-depth: 0
                #persist-credentials: false
          - name: assume creator Role
            #uses: ./
            uses: aws-actions/configure-aws-credentials@v6 #REPLACE THIS
            with:
                aws-region: us-west-2
                role-to-assume: ${{ secrets.STATIC_USER_CREATION_ROLE }}

          - name: create access key and remove session token (so we can log in to static role)
            run: | 
                aws iam create-access-key --user-name integ-test-static-user-${{ runner.os }} | jq -r '"STATIC_ACCESS_KEY_ID=\(.AccessKey.AccessKeyId)\nSTATIC_SECRET_ACCESS_KEY=\(.AccessKey.SecretAccessKey)"' >> $GITHUB_ENV


          - name: sleep on it
            run: sleep 30

          - name: try logging in w static access key
            uses: aws-actions/configure-aws-credentials@v6 #REPLACE THIS
            with:
                aws-region: us-west-2
                role-to-assume: static-creds-test-role-to-assume
                aws-access-key-id: ${{ env.STATIC_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ env.STATIC_SECRET_ACCESS_KEY }}

          - name: check who we are
            run: aws sts get-caller-identity

          - name: log back into creator role
            #uses: ./
            uses: aws-actions/configure-aws-credentials@v6 #REPLACE THIS
            with:
                aws-region: us-west-2
                role-to-assume: ${{ secrets.STATIC_USER_CREATION_ROLE }}

          - name: delete user
            run: |
                aws iam delete-access-key --user-name integ-test-static-user-${{ runner.os }} --access-key-id ${{ env.STATIC_ACCESS_KEY_ID }}
            #    aws iam delete-user --user-name integ-test-static-user-${{ runner.os }}
