name: test no env outputs
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: try first region
        id: creds1
        uses: aws-actions/configure-aws-credentials@aeb7571
        with: 
          role-to-assume: arn:aws:iam::891612571239:role/githubActionTest-Role-5YBrxygEBfRs
          aws-region: us-east-1

      

