name: unset-creds-test-7
on:
  workflow_dispatch:

jobs:
  cawsc: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        id: firstCreds
        uses: aws-actions/configure-aws-credentials@test-ghaction-input
        with: 
          role-to-assume: arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test
          aws-region: ${{ vars.AWS_REGION }}
        
        

       