name: unset-creds-test-7
on:
  workflow_dispatch:

jobs:
  cawsc: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # I expect this to populate a bunch of `AWS_` variables, which it does correctly.
      - name: set env
        run: |
          env "INPUT_AWS-REGION=us-east-1" "INPUT_ROLE-TO-ASSUME=arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test" bash
      - name: Configure AWS Credentials
        id: firstCreds
        uses: aws-actions/configure-aws-credentials@test-ghaction-input
        
        

       