name: unset-creds-test-4
on:
  workflow_dispatch:

jobs:
  cawsc:  
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # I expect this to populate a bunch of `AWS_` variables, which it does correctly.
      - name: Configure AWS 
        id: hi
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test
          output-credentials: true

      # I expect this to be able to use the `AWS_` variables, which it does correctly
      - name: Terraform init
        run: echo ${{ steps.hi.outputs.aws-session-token }}

      # I expect this to be able to use the `AWS_` variables, which it does correctly
      - name: Terraform plan
        id: plan
        run: |
          echo $AWS_SESSION_TOKEN
          echo $AWS_ACCESS_KEY_ID

      # I expect this to wipe the `AWS_` variables, but instead it errors out
      - name: Unset terraform aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          unset-current-credentials: true
          role-to-assume: arn:aws:iam::891612571239:role/Chime-Read-CAWSC-Test

      # This last step and any subsequent step should no longer have any access to AWS credentials
      - name: Some random thing that might be insecure and even if its secure, it doesn't need AWS credentials
        run: echo $AWS_REGION

  cawscagain:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: try to access env variable
        run: |
            echo $AWS_REGION
            echo ${{ steps.hi.outputs.aws-session-token }}
