name: unset-creds-test-8
env:
  AWS_REGION: 'us-east-1'
  ROLE_TO_ASSUME: 'arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test'
on:
  workflow_dispatch:

jobs:
  cawsc: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test
          role-session-name: My Session Name
            