name: unset-creds-test-7
env: 
  audience: asdfjkl
on:
  workflow_dispatch:

jobs:
  cawsc: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        id: firstCreds
        uses: aws-actions/configure-aws-credentials@environment-variables
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test
          audience: sts.amazonaws.com
        
        

       