name: unset-creds-test-9
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS - Region 1
        uses: aws-actions/configure-aws-credentials@v4.2.0
        with:
          role-to-assume: arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test
          aws-region: eu-west-2

      - name: Check Region 1
        run: echo "AWS_REGION=$AWS_REGION"

      - name: Configure AWS - Region 2
        uses: aws-actions/configure-aws-credentials@v4.2.0
        with:
          role-to-assume: arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test
          aws-region: ap-southeast-1

      - name: Check Region 2
        run: |
          echo "AWS_REGION=$AWS_REGION"