name: unset-creds-test-7
env: 
  INPUT_AUDIENCE: whoever
on:
  workflow_dispatch:

jobs:
  cawsc: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # I expect this to populate a bunch of `AWS_` variables, which it does correctly.
      - name: Configure AWS Credentials
        id: firstCreds
        uses: aws-actions/configure-aws-credentials@test-ghaction-input
        
        

       