name: unset-creds-test-7
env:
  AWS-REGION: us-east-1
  ROLE-TO-ASSUME: arn:aws:iam::891612571239:role/S3-Read-CAWSC-Test
on:
  workflow_dispatch:

jobs:
  cawsc: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        id: firstCreds
        uses: aws-actions/configure-aws-credentials@environment-variables
        
        

       