name: v1 static test
on:
    workflow_dispatch:

jobs:
    do-the-thing:
        name: test out role chaining account number
        runs-on: ubuntu-latest
        steps:
            
          - name: first static
            id: static-1
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-access-key-id: ${{ secrets.STATIC_1_AK_ID }}
                aws-secret-access-key: ${{ secrets.STATIC_1_SECRET_AK }}
                aws-region: us-east-1
          
          - name: Debug build spoke identity
            run: |
                aws sts get-caller-identity